### ISSUE TITLE
Missing file eband_local_planner/EBandPlannerConfig.h when catkin build the ros-autom fork

### ISSUE THREAD

**Issue by Shentheman** [utexas-bwi/eband_local_planner#24]
I was trying to build the fork [`ros-autom/eband_local_planner`](https://github.com/ros-autom/eband_local_planner) without doing `sudo apt-get install ros-indigo-eband-local-planner`. I have an error about the missing file [`eband_local_planner/EBandPlannerConfig.h`](https://github.com/Shentheman/eband_local_planner/blob/kinetic/include/eband_local_planner/eband_visualization.h#L46).

But if I install the the release version of the original [`utexas-bwi/eband_local_planner`](https://github.com/utexas-bwi/eband_local_planner) first by `$ sudo apt-get install ros-indigo-eband-local-planner` first, I can build the  ros-autom fork.

I think it might be a bug? But I am not sure about your implementation structure though :)

I really like the ros-autom fork because it has the dynamic reconfigure function.

Thank you!

**Comment by piyushk** [comment]
I can't comment about the ros-autom fork, so I will close this issue. If it's also happening here, please let me know.

We've just merged in dynamic reconfigure in #22. A few more updates are incoming, and then we'll make a new release.

**Comment by piyushk** [comment]
@Shentheman: I suddenly realized that the error you mentioned might be because of missing dependency on the generated config. See the `add_dependencies` calls here: add_dependencies(your_program ${your_package_EXPORTED_TARGETS})
add_dependencies(your_library ${your_package_EXPORTED_TARGETS})

In short, the package is compiling the library as well as generating the config, but doesn't know that the library depends on the config and the config must be generated first. This results in a race condition, and should lead to non-deterministic build success when you build from scratch.
